// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Skincare.Repositories.Models;

[Table("CustomerServiceHistory")]
public partial class CustomerServiceHistory
{
    [Key]
    public int CustomerId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string CustomerName { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string PhoneNumber { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string ServiceUsed { get; set; }

    public DateOnly ServiceDate { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? ServicePrice { get; set; }

    public int? ServiceRating { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string ServiceResult { get; set; }

    public int? ProviderId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string PromotionApplied { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string ReasonForService { get; set; }

    [ForeignKey("ProviderId")]
    [InverseProperty("CustomerServiceHistories")]
    public virtual ServiceProviderInfo Provider { get; set; }
}