// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Skincare.Repositories.Models;

[Table("ServiceProviderInfo")]
public partial class ServiceProviderInfo
{
    [Key]
    public int ProviderId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string ProviderName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string ServiceType { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Address { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string ContactNumber { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string WorkingHours { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string SpecialistInCharge { get; set; }

    public int? ProviderRating { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Promotions { get; set; }

    [InverseProperty("Provider")]
    public virtual ICollection<CustomerServiceHistory> CustomerServiceHistories { get; set; } = new List<CustomerServiceHistory>();
}